In [55]:
import pandas as pd
import re

from amz_local_search.resources.fba_centers import fba_centers_info
from amz_local_search.resources.states.us_state_abbrev import us_state_abbrev

In [56]:
# List taken from https://en.wikipedia.org/wiki/List_of_largest_cities_of_U.S._states_and_territories_by_population
wiki_pop_df = pd.read_csv('/Users/evgenyp/Projects/AmzJet/AmzJet/amz-apps/amz_local_search/resources/references/State Cities by Population.tsv', sep='\t')
wiki_pop_df.head(3)

,"State, Federal District, or Territory","State, Federal District, or Territory Population[5]",Most populous,City population,2nd most populous,3rd most populous,4th most populous,5th most populous,Capital (if not otherwise listed)
0,Alabama,"4,887,871",Birmingham,"209,880","Montgomery(198,218)","Huntsville(197,318)","Mobile(189,572)","Tuscaloosa(101,113)[6]",NaN
1,Alaska,"737,438",Anchorage,"291,538","Juneau(32,113)","Fairbanks(31,516)","Wasilla(10,529)","Sitka(8,647)",NaN
2,American Samoa,"55,519[7]",Tafuna,"7,945[8]","Pago Pago(3,656)","Nu'uuli(3,346)","Ili'ili(3,195)","Pava'ia'i(2,450)","Fagatogo(10) (1,737)"

In [57]:
wiki_pop_df['State'] = wiki_pop_df['State, Federal District, or Territory'].map(lambda s: us_state_abbrev.get(s))

In [61]:
wiki_pop_df_cleaned = wiki_pop_df[pd.notnull(wiki_pop_df['State'])][['State', 'State, Federal District, or Territory Population[5]', 'Most populous']]
wiki_pop_df_cleaned.columns = ['state', 'population', 'major_city']
wiki_pop_df_cleaned['major_city'] = wiki_pop_df_cleaned['major_city'].map(lambda n: re.split('\d', n)[0])
wiki_pop_df_cleaned['population'] = wiki_pop_df_cleaned['population'].map(lambda s: s.replace(',', '')).astype(int)

wiki_pop_df_cleaned['num_fba_codes'] = wiki_pop_df_cleaned['state'].map(lambda s: len(fba_centers_info.state_to_codes(s)))

#wiki_pop_df_cleaned.set_index('state', inplace=True)
wiki_pop_df_cleaned.to_csv('/Users/evgenyp/Projects/AmzJet/AmzJet/amz-apps/amz_local_search/resources/states/facts.tsv', sep='\t')
wiki_pop_df_cleaned.to_dict(orient='records')

[{'major_city': 'Birmingham',
  'num_fba_codes': 3,
  'population': 4887871,
  'state': 'AL'},
 {'major_city': 'Anchorage',
  'num_fba_codes': 0,
  'population': 737438,
  'state': 'AK'},
 {'major_city': 'Phoenix',
  'num_fba_codes': 13,
  'population': 7171646,
  'state': 'AZ'},
 {'major_city': 'Little Rock',
  'num_fba_codes': 0,
  'population': 3013825,
  'state': 'AR'},
 {'major_city': 'Los Angeles',
  'num_fba_codes': 72,
  'population': 39557045,
  'state': 'CA'},
 {'major_city': 'Denver',
  'num_fba_codes': 6,
  'population': 5695564,
  'state': 'CO'},
 {'major_city': 'Bridgeport',
  'num_fba_codes': 4,
  'population': 3572665,
  'state': 'CT'},
 {'major_city': 'Wilmington',
  'num_fba_codes': 4,
  'population': 967171,
  'state': 'DE'},
 {'major_city': 'Washington',
  'num_fba_codes': 0,
  'population': 702455,
  'state': 'DC'},
 {'major_city': 'Jacksonville',
  'num_fba_codes': 30,
  'population': 21299325,
  'state': 'FL'},
 {'major_city': 'Atlanta',
  'num_fba_codes': 20,
  'population': 10519475,
  'state': 'GA'},
 {'major_city': 'Honolulu',
  'num_fba_codes': 0,
  'population': 1420491,
  'state': 'HI'},
 {'major_city': 'Boise',
  'num_fba_codes': 0,
  'population': 1754208,
  'state': 'ID'},
 {'major_city': 'Chicago',
  'num_fba_codes': 28,
  'population': 12741080,
  'state': 'IL'},
 {'major_city': 'Indianapolis',
  'num_fba_codes': 15,
  'population': 6691878,
  'state': 'IN'},
 {'major_city': 'Des Moines',
  'num_fba_codes': 0,
  'population': 3156145,
  'state': 'IA'},
 {'major_city': 'Wichita',
  'num_fba_codes': 8,
  'population': 2911505,
  'state': 'KS'},
 {'major_city': 'Louisville',
  'num_fba_codes': 22,
  'population': 4468402,
  'state': 'KY'},
 {'major_city': 'New Orleans',
  'num_fba_codes': 0,
  'population': 4659978,
  'state': 'LA'},
 {'major_city': 'Portland',
  'num_fba_codes': 0,
  'population': 1338404,
  'state': 'ME'},
 {'major_city': 'Baltimore',
  'num_fba_codes': 12,
  'population': 6042718,
  'state': 'MD'},
 {'major_city': 'Boston',
  'num_fba_codes': 7,
  'population': 6902149,
  'state': 'MA'},
 {'major_city': 'Detroit',
  'num_fba_codes': 6,
  'population': 9995915,
  'state': 'MI'},
 {'major_city': 'Minneapolis',
  'num_fba_codes': 5,
  'population': 5611179,
  'state': 'MN'},
 {'major_city': 'Jackson',
  'num_fba_codes': 1,
  'population': 2986530,
  'state': 'MS'},
 {'major_city': 'Kansas City',
  'num_fba_codes': 2,
  'population': 6126452,
  'state': 'MO'},
 {'major_city': 'Billings',
  'num_fba_codes': 0,
  'population': 1062305,
  'state': 'MT'},
 {'major_city': 'Omaha',
  'num_fba_codes': 0,
  'population': 1929268,
  'state': 'NE'},
 {'major_city': 'Las Vegas',
  'num_fba_codes': 12,
  'population': 3034392,
  'state': 'NV'},
 {'major_city': 'Manchester',
  'num_fba_codes': 1,
  'population': 1356458,
  'state': 'NH'},
 {'major_city': 'Newark',
  'num_fba_codes': 27,
  'population': 8908520,
  'state': 'NJ'},
 {'major_city': 'Albuquerque',
  'num_fba_codes': 0,
  'population': 2095428,
  'state': 'NM'},
 {'major_city': 'New York City',
  'num_fba_codes': 4,
  'population': 19542209,
  'state': 'NY'},
 {'major_city': 'Charlotte',
  'num_fba_codes': 8,
  'population': 10383620,
  'state': 'NC'},
 {'major_city': 'Fargo',
  'num_fba_codes': 0,
  'population': 760077,
  'state': 'ND'},
 {'major_city': 'Saipan',
  'num_fba_codes': 0,
  'population': 53883,
  'state': 'MP'},
 {'major_city': 'Columbus',
  'num_fba_codes': 17,
  'population': 11689442,
  'state': 'OH'},
 {'major_city': 'Oklahoma City',
  'num_fba_codes': 3,
  'population': 3943079,
  'state': 'OK'},
 {'major_city': 'Portland',
  'num_fba_codes': 7,
  'population': 4190713,
  'state': 'OR'},
 {'major_city': 'Philadelphia',
  'num_fba_codes': 26,
  'population': 12807060,
  'state': 'PA'},
 {'major_city': 'San Juan',
  'num_fba_codes': 0,
  'population': 3195153,
  'state': 'PR'},
 {'major_city': 'Providence',
  'num_fba_codes': 0,
  'population': 1057315,
  'state': 'RI'},
 {'major_city': 'Charleston',
  'num_fba_codes': 4,
  'population': 5084127,
  'state': 'SC'},
 {'major_city': 'Sioux Falls',
  'num_fba_codes': 0,
  'population': 882235,
  'state': 'SD'},
 {'major_city': 'Nashville',
  'num_fba_codes': 10,
  'population': 6770010,
  'state': 'TN'},
 {'major_city': 'Houston',
  'num_fba_codes': 45,
  'population': 28701845,
  'state': 'TX'},
 {'major_city': 'Salt Lake City',
  'num_fba_codes': 2,
  'population': 3161105,
  'state': 'UT'},
 {'major_city': 'Burlington',
  'num_fba_codes': 0,
  'population': 626299,
  'state': 'VT'},
 {'major_city': 'Virginia Beach',
  'num_fba_codes': 11,
  'population': 8517685,
  'state': 'VA'},
 {'major_city': 'Seattle',
  'num_fba_codes': 24,
  'population': 7535591,
  'state': 'WA'},
 {'major_city': 'Charleston',
  'num_fba_codes': 0,
  'population': 1805832,
  'state': 'WV'},
 {'major_city': 'Milwaukee',
  'num_fba_codes': 4,
  'population': 5813568,
  'state': 'WI'},
 {'major_city': 'Cheyenne',
  'num_fba_codes': 0,
  'population': 577737,
  'state': 'WY'}]

In [63]:
len(fba_centers_info.state_to_codes('CA'))

72

In [64]:
wiki_pop_df_cleaned['num_fba_codes'].sum()

463